version: "3.6"

services:
  catalog-testing:
    image: "maven:3-alpine"
    container_name: catalog-testing
    hostname: catalog-testing
    volumes:
     - type: bind
       source: ./saps-catalog
       target: /saps-catalog-repo
     - type: bind
       source: ./saps-common
       target: /saps-common-repo
    command: sleep 3600
   
  catalog-docs:
    image: "sphinxdoc/sphinx"
    container_name: catalog-docs
    hostname: catalog-docs
    volumes:
     - type: bind
       source: ./saps-catalog
       target: /saps-catalog-repo
    command: sleep 3600
